### ISSUE TITLE
Sell menu crashes or broken when max inventory size is less than screen size

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#11]
Sell menu is horribly and painfully broken when max inventory size is less than one screenful

**Comment by rversteegen** [comment]
Definitely a release-blocker... not just because it turns out that it causes crashes in a number of games.

Have three crash reports for this (4445d2bf, d48c50da, 2e5ba8cd), all with identical backtrace:

```
----- Stacktrace -----
@ [game.exe + 0x1e497c]
@ [game.exe + 0x1e3605]
@ SELLSTUFF            	(menustuf.rbas:1770 + 0x28)
   1768   ELSE
   1769    item_name = inventory(i).text
 ->1770   END IF
   1771   printstr item_name, 20 + 96 * (i MOD 3), 12 + 8 * ((i - top) \ 3), page
@ SHOP                 	(moresubs.rbas:1650 + 0x15)
   1648   IF menuid(st.pt) = 1 THEN '--SELL
   1649    sellstuff id, storebuf()
 ->1650   END IF
   1651   IF menuid(st.pt) = 2 THEN '--HIRE
@ ADVANCE_TEXT_BOX     	(game.bas:3482 + 0x9)
   3480   IF txt.box.shop > 0 THEN
   3481    shop txt.box.shop - 1
 ->3482   ELSEIF txt.box.shop < 0 THEN
   3483    '--Preserve background for display beneath the top-level shop menu
@ main + 0x35fc (game.exe)
@ [game.exe + 0x126d]
@ __RtlUserThreadStart + 0x2f (ntdll.dll)
@ _RtlUserThreadStart + 0x1b (ntdll.dll)
```

(The unmarked frame at the top is in fb_StrAssign: I believe it's crashing due to heap or stack corruption)

**Comment by rversteegen** [comment]
Fixed in r11282. Turns out the bug was introduced in nightlies by r10326, which added (incorrectly one-sided) bounds checking for the `top` variable. Before that, we had been safely reading past last_inv_slot(), because inventory() is always sized to inventoryMax.
