### ISSUE TITLE
Can escape unescapable enemies who are jumping

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1107]
If an enemy with the Unescapeable bit jumps off-screen, then you can run from battle.

Is this a bug, or a feature? Should we add a backcompat bit or a battle system pref bit to toggle it?

It happens because:
```
FUNCTION checkNoRunBit (bslot() as BattleSprite) as bool
 FOR i as integer = 4 TO 11
  IF bslot(i).stat.cur.hp > 0 AND bslot(i).vis = YES AND bslot(i).unescapable = YES THEN RETURN YES
 NEXT i
 RETURN NO
END FUNCTION
```
`BattleSprite.vis` is false while an combatant has jumped offscreen.
`vis` is used for many different purposes in many different places. I know it's short for "visible", but I spent an hour trying to figure out what it *actually* means. There are a set of exceptions (which I've now documented), and I consider any code that makes use of `vis` as suspect.

**Comment by bob-the-hamster** [comment]
Definitely a bug. Should not have a backcompat bit

However, it would be nifty to have a feature that could turn the unescapable bit off and on mid battle

**Comment by rversteegen** [comment]
This was fixed by James by the "bare minimum of cleanup" in r12690!
