### ISSUE TITLE
gfx_sdl/sdl2: can't resize the window on older xfce4

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1115]
Attempting to resize the window moves it instead, running with gfx_sdl under FreeBSD 11 p9 and xfce. 
The WM mouse cursor changes to the moving icon as soon as you click on the window frame. Alt+right mouse doesn't resize the window either. 

I don't know whether this is specific to FreeBSD or xfce or both, or whether it's an SDL 1.2 bug, but I couldn't find any other mention online of such a bug.

I couldn't test gfx_sdl2 because I'm not a FreeBSD user and haven't yet figured out how to find a suitably old SDL2 port and install it on an unsupported FreeBSD release.

**Comment by bob-the-hamster** [comment]
We support window resizing by dragging?


I use Xfce, and the only type of window resizing that has ever worked for
me is maximize/unmaximize

**Comment by rversteegen** [comment]
?!
Yes, when the window is set to resizable (e.g. everywhere in Custom, also the in-game slice debugger) you should be able to resize the window like any other program. Resizing other windows by dragging the border works for me in Xfce (on FreeBSD).

Again, I can't find any mention online about resizeable windows being broken in SDL+Xfce.

**Comment by bob-the-hamster** [comment]
I had always thought that free resizing was Windows only. I do use
maximizing all the time

I don't have any trouble with resizing other windows on Xfce, but I don't
know another SDL game that allows window resizing that I could try.


---
James Paige

**Comment by rversteegen** [comment]
Does gfx_sdl2 have the same problem?

SDL has a number of test programs for example [testwm.c](
https://hg.libsdl.org/SDL/raw-file/ab7529cb9558/test/testwm.c)
(Compile with `gcc -o testwm testwm.c -lSDL -I/usr/include/SDL` and run
with `./testwm -resize`; it takes a number of other args too)

Well, I do have xfce installed on this machine so could test this out
myself sometime.

**Comment by bob-the-hamster** [comment]
I can't believe I had not tested gfx_sdl2 yet! I had to do apt-get install
libsdl2-dev libsdl2-mixer-dev

gfx_sdl2 resizes just fine.

I ran testwm -resize and it was able to resize just fine.

I also discovered a workaround for gfx_sdl

When I first launch custom, and attempt to resize will just move the whole
window over.
If I press CTRL+F7 and re-switch to the gfx_sdl backend (even without
switching to another backend) then suddenly the window resizing works
properly.

---
James Paige

**Comment by rversteegen** [comment]
That's very interesting. It's good news that it's our bug: we can fix it.

On startup, Custom calls `unlock_resolution 320, 200` immediately after creating the window, to make it resizable, so the problem must be related to that.

I also have a branch to make Custom remember its window size on startup, which worked by resizing the window immediately after creating it, but that can also cause problems (under X11/KDE), so it seemed necessary to instead tell the backend what the initial window size should be. That ought to fix this bug too.

**Comment by rversteegen** [comment]
> I also have a branch to make Custom remember its window size on startup, which worked by resizing the window immediately after creating it, but that can also cause problems (under X11/KDE)

IIRC the problem was that delayed window resize WM events randomly cause gfx_sdl to change the window size back to 320x200

**Comment by rversteegen** [comment]
I recently switched to xfce4 from KDE4 because I was sick of how slow KDE was (although I suspect there was something wrong with my installation). Anyway I found that the window still isn't resizable when using gfx_sdl2. Got to remove that bugfix note from whatsnew.txt.

Also the other day every time that the engine attempted to toggle window resizability (e.g. when opening the Debug Menu ingame) it would flicker black, but it's not doing that today.

**Comment by rversteegen** [comment]
I just upgraded to xfce 4.16 (released 22/12/2020) from 4.12, and this bug is now gone (tested with SDL 1.2.15, 2.0.12 and 2.0.14). Do you still see the same problem, James?

Also, I noticed that window resizing did work under xfce 4.12 once Custom/Game switched the window from non-resizable to resizable. For example this happens while the F8 debug menu is open (although I'm considering getting rid of that behaviour). I still expect merging the branch I mentioned previously will fix this:
> I also have a branch to make Custom remember its window size on startup,

**Comment by rversteegen** [comment]
I'm marking this resolved: obsolete because it's fixed in (quite recent) xfce versions.
