### ISSUE TITLE
SDL_mixer crash on 64-bit Mac when looping/loading a MIDI

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1128]
Ravancloak twice had a crash while playing [I AM BEAN BOY](https://www.slimesalad.com/forum/viewgame.php?p=137050), and also other audio glitches.

> rue9x: she also said that when the "beep" sound plays (there's a on-step script that plays a footfall beep sound) all of the audio cut out
> rue9x: but that might have been coincidental

Here is the OSX-generated crash log: [bean_boy_crash.txt](https://github.com/ohrrpgce/ohrrpgce/files/4640252/bean_boy_crash.txt)

Mac OS X 10.13.6
O.H.R.RPG.C.E version gorgonzola 20200502 (x86_64)
SDL 1.2.14
SDL_mixer 1.2.11

The log shows that the crash happens inside SDL_mixer when the mixing thread dereferences `music_playing->type` (this code-path occurs only on Mac) while the main thread is in the process of loading a MIDI (inside `native_midi_start` in a `Mix_FadeInMusicPos` call). So this is apparently clearly a race condition in SDL_mixer, and their bug.

SDL_mixer 1.2.11 is out of date, 1.2.12 has "Fixed looping native MIDI on Mac OS X and Windows" in the changelog. I'd like to verify that 1.2.12 actually fixes this, though. It looks like there will be one more SDL_mixer 1.2 bugfix release soon.

**Comment by rversteegen** [comment]
64-bit Mac builds are crashing on MIDIs, as SDL_mixer.framework on the Mac nightly build machine also needs to be upgraded, from the ancient version 1.2.11 to the latest 1.2.12 (released 2012). Sorry James, I forgot to ask you to do this when upgrading SDL.framework (for #1138). `mac/get_sdl_frameworks.sh` already points at 1.2.12. (Aside: `mac/Frameworks.tar.gz` contains a 32-bit build of SDL_mixer 1.2.11 which I [had patched](http://tmc.castleparadox.com/freebasic/SDL_mixer_macmidi_fix_wip.patch) to fix MIDI looping, apparently fixing this crash without knowing it)

> Charbomber: It seems that the current version of the OHRRPG Game app crashes whenever it reaches the end of a midi. I'm not sure if it's for other versions, but it crashes on Mac whenever the player gets teleported to a new area after the end of a midi. Also, midi's don't loop, but I think the crash is a bigger issue.

**Comment by bob-the-hamster** [comment]
I installed SDL_mixer.framework 1.2.12 into /Library/Frameworks/ on the Mac
nightly build machine, and forced an early nightly build.

I hope it helps :D

---
James Paige

**Comment by rversteegen** [comment]
Charbomber never got back to me to say that it was fixed. But I'm quite certain it is, since it's listed as fixed in the SDL_mixer changelog.
