### ISSUE TITLE
Can't push NPCs using mouse controls

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1134]
Right now, I can't think of how this would even work.

**Comment by bob-the-hamster** [comment]
Oh! Hmm.... That is a tricky one!

What if we make a special-case gesture for that?

Like if you touch on an NPC drag in a direction and release, then the hero will path over to that NPC and attempt a push in that direction.

I think that will work very well for non-moving non-activating NPCs like block-pushing puzzle NPCs

Moving and talking NPCs will get trickier, but I think if we tune the gesture distance carefully it could work.

**Comment by rversteegen** [comment]
Dragging could work... but I think we should probably have a visual indicator that you can push an NPC. Maybe if you mouse-over the NPC an arrow could appear in each direction in which you can push it. Alternatively (and closer to how keyboard controls work -- no hinting that an NPC is pushable until you try it), if you're standing next to a pushable NPC and mouse over it, an arrow could appear on the other side indicating you can push it. We could even allow clicking the arrow instead of dragging. (If you move the mouse away from the NPC the arrow could disappear, allowing you to click on the tile behind to path there instead).

There could be a default pushability icon which you can customise. I want to add a couple new sprite types for cursors and icons.

EDIT: I split off the rest of this comment to #1141

**Comment by bob-the-hamster** [comment]
I now prefer a simpler solution

Clicking a distant NPC just paths to it and tries to activate it (current behavior)

While standing next to a pushable NPC, clicking on it will attempt to push it.

If the NPC is both activatable and pushable, it should activate first, then push after the text box chain is done

**Comment by rversteegen** [comment]
Yes, it just isn't necessary to support 100% of existing games; very many of them have scripted keyboard controls anyway!

I think that dragging to push (as an alternative) might not be very difficult to implement, but wouldn't be a high priority.

Also, does this mean you're implementing Bump NPC activation??

**Comment by bob-the-hamster** [comment]
I have implemented a fix for this.

What I settled on is slightly different from what I described above for the case of an NPC that can be both pushed and activated, but I think I like it...

Click on a distant NPC, always activates, never pushes

Click on a nearby NPC, pushes if possible, activates if the pushable npc can't be moved because there is an obstruction in the way.

I played with this for a while, and it seems intuitive for both puzzle-npcs that you might activate for a help-hint, and townspeople who you are allowed to shove out of the way but might also want to talk to

**Comment by rversteegen** [comment]
This seems usually good, although after a couple minutes experimentation I do hit into the annoyance of pushing an NPC I wanted to activate. I still suspect that standing next to an NPC and dragging from the hero to the NPC could be a natural solution - NPCs are activated by mouse click, not mouse release, but since you'd be clicking on the hero (whcih does nothing) instead of the NPC, that's not a problem. And defaulting to pushing if they aren't activatable.

It seems that you can push unpushable NPCs by clicking on them! If they can't be pushed because of an obstruction or because they have 0 speed, then you walk on top of them.

**Comment by bob-the-hamster** [comment]
Oops! I guess I didn't test enough!
I'll fix it so it stops trying to push NPCs that aren't pushable

But I see what you mean about the annoyance of pushing an NPC you want to activate. Some games will quite reasonably make all townspeople pushable, and not being able to activate them from one tile away could get annoying.

I'll keep the current behavior for NPCs that are only pushable and not activatable, but I guess I will need to implement some dragging logic also

**Comment by bob-the-hamster** [comment]
Okay, this is done. Here is the final behavior

* Clicking on an NPC far away, always paths to it and activates it. Does no pushing.
* Clicking on a nearby activatable NPC activates it. Doesn't matter whether it is pushable
* Clicking on a nearby non-activatable pushable NPC always pushes it
* Dragging from the hero to a nearby NPC always pushes it, doesn't matter whether it is activatable.

This feels nice and confortable for all combinations except for activatable+pushable that moves frequently on its own. Those err on the side of activation. They are still pushable, but it is slightly awkward. I think this is fine, and is no worse than the awkwardness of trying to push fast-moving NPCs with the keyboard controls. Also I can't think of a situation where pushing a fast moving NPC matters in a real game :D

I am marking this complete
