### ISSUE TITLE
Can't distribute for Linux: "tar.exe reported failure" or "couldn't run tar"

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1157]
Both distributing a .deb or a .tar.gz for Linux are broken, at least when running on Windows, when either the path to tar.exe (in support/) contains a space, or the name of the game (and hence .tar filename). They both call `create_tarball`.

This is apparently two different very similar bugs.
The first (I couldn't figure out what encoding this is) is demonstrated by:
> 1573,1  C:\Users\Admin\Google Äèñê\OHRRPGCE\Polaris\0_Distant Polaris\SDL2\support\tar.exe --version > "C:\Users\Admin\AppData\Roaming\OHRRPGCE\temp_stdout.518281.tmp" 2> "C:\Users\Admin\AppData\Roaming\OHRRPGCE\temp_stderr.99769.tmp"
> 1573,3  safe_shell()=1 stderr:"C:\Users\Admin\Google" ­¥ ï¢«ï¥âáï ¢­ãâà¥­­¥© ¨«¨ ¢­¥è­¥©
> ª®¬ ­¤®©, ¨á¯®«­ï¥¬®© ¯à®£à ¬¬®© ¨«¨ ¯ ª¥â­ë¬ ä ©«®¬.
> 
> 1573,3  ! ERROR: couldn't run tar
> "C:\Users\Admin\Google" ­¥ ï¢«ï¥âáï ¢­ãâà¥­­¥© ¨«¨ ¢­¥è­¥©
> ª®¬ ­¤®©, ¨á¯®«­ï¥¬®© ¯à®£à ¬¬®© ¨«¨ ¯ ª¥â­ë¬ ä ©«®¬.

That last ERROR is shown on the screen.

The second happens when there's a space in the .tar file, it shows an error "tar.exe reported failure, errorcode 2"

**Comment by rversteegen** [comment]
Prifurin suggested the characters "-" and "()" in the path to the engine also broke packaging of .debs and linux tarballs. I haven't tested that.

**Comment by bob-the-hamster** [comment]
I can reproduce this bug on both Windows and Linux.

Linux doesn't show the same error message, but fails in a similar way to windows

**Comment by bob-the-hamster** [comment]
I have comited a fix and verified it on both Windows and Linux.
This was happening because quoting and escaping was required for an argument of `create_tarball()` but was not actually being done in the case of Linux distrib tarballs.
