### ISSUE TITLE
MP~ cannot be set  above 100 in hero editor; Extra Hits has a lower cap.

### ISSUE THREAD

**Issue by NathanWeasel** [ohrrpgce/ohrrpgce#1176]
In order to actually get the stat to level on a certain curve in games with lower level caps than 99, there would need to be options to set the stat to values higher than 100 as with the other stats (for example, a game with a max level of 9 you won't really get an appreciable amount of MP~ if its starting value is 0 and its ending value is 100 and you can't set the level 99 MP~ to something like 255 or 420 to see if those would get you anywhere). In any game where spells don't cost any MP (for example, using item consumption or Level MP as the primary spellcasting costs) any possible weird interactions numbers higher than 100 might have with MP costs would be irrelevant anyway.

Likewise, the Hits can be disabled entirely on a game by game basis, but there's still no option to raise it sky high in the hero editor.

MP not deducted = it and MP~ both serve as "dummy stats" that can do various other things the way CTR does
"Attacks ignore the Extra Hits stat" general game bitset = it can also serve as a "dummy stat" like CTR

But MP~ and Hits still have arbitrarily low maximums, whereas these have been lifted on HP, MP, ATK, AIM, DEF, DOG, MAG, WIL,  SPD, and CTR.

**Comment by NathanWeasel** [comment]
![new RPG0021](https://user-images.githubusercontent.com/62185664/94064687-0bae3f00-fdb8-11ea-9001-d73ebee5d5be.png)

**Comment by rversteegen** [comment]
OK, the hero and enemy editors now limit all stats to 32767 (the stat caps menu already did so). Also, there is a new general bit, "Ignore the MP~ stat", so you can have up to three free stats.
