### ISSUE TITLE
Increase max-size of compiled scripts

### ISSUE THREAD

**Issue by CronosZX** [ohrrpgce/ohrrpgce#1177]
I don't know how plausible this would be or if it has been suggested but the current max size of 256kb, although enough for most projects, will probably not be enough for a bit of a long term project I'm working on that's sitting at 116kb (although not very optimized) and I'm afraid I'll run out of space before I'm finished.

**Comment by rversteegen** [comment]
256KB is the max size of a *single* compiled script, which is enormous so you'll never hit it. There's no limit to the total size of the .hs file.

But, there's no real reason to have that limit at all, so I've just removed it.
