### ISSUE TITLE
ohrrpgce*.deb broken: "Error:Dependency is not satisfiable: libsdl2-mixer (>= 2.0)"

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1192]
Idontknow reports that the nightly ohrrpgce_*.wip-*_amd64.deb package can't be installed because I got the dependency wrong. Originally I added "libsdl2-mixer (>= 2.0.0)" to the dependencies which resulted in "Error:Dependency is not satisfiable: libsdl2-mixer (>= 2.0.0)", so I changed it to (>= 2.0) and that still doesn't work and I don't understand why. Now in this case the version doesn't matter but I wanted to specify a version so we can increase it later.

**Comment by bob-the-hamster** [comment]
We should find out exactly which version of which debian-derived distro Idontknow is using.

(But I'll also do some testing myself)

**Comment by rversteegen** [comment]
It's Linux Mint but Idontknow didn't remember which version, but probably the latest. He has libsdl2-mixer-2.0-0 installed.
