### ISSUE TITLE
Wiki inaccessible with Chrome (ERR_INCOMPLETE_CHUNKED_ENCODING)

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1199]
Prifurin says they haven't been able to access the wiki using Chrome for about a year! (Firefox works fine.) All access attempts produce a blank page. Chrome gives the error message:
``Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING <pagename>:1``

I looked in the server access logs and there are no errors logged, just a successful connection (status 200), eg:

``<ip address> - - [12/Mar/2021:05:31:54 -0800] "GET /ohrrpgce/Category:Advice HTTP/1.1" 200 9857 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" ``

**Comment by rversteegen** [comment]
Pages outside the wiki, such as the nightly builds directory, seem to work.

I found one blogpost where someone said they fixed this error by disabling their antivirus's realtime protection! Ughhh

**Comment by bob-the-hamster** [comment]
I tested with Chrome on Mac, and Chromium on Linux and had no problems, so it definitely isn't all Chromes. Maybe Prifurin can narrow down exactly which version they are using on which OS?

**Comment by bob-the-hamster** [comment]
Oh, the antivirus thing makes me wonder if it is not a Chrome problem, but a problem with the Chrome extension for a specific Antivirus program?

**Comment by NathanWeasel** [comment]
I've been using Chrome almost exclusively for a bit over a decade with no issues either, always up to date.

**Comment by rversteegen** [comment]
Prifurin: No, disabling antivirus doesnt change anything
tmc: do you have any extensions/addons installed in chrome that might be part of the virus scanner?
Prifurin: Oh right, there's one
tmc: is it possible to disable it?
Prifurin: Yes, but that also doesnt change anything
Prifurin: I can access Hamsterrepublic, plotscript dictionary and nightly builds pages
Prifurin: but https://rpg.hamsterrepublic.com/ohrrpgce/Main_Page doesnt load

**Comment by rversteegen** [comment]
Prifurin says the problem is gone. Closing.
