### ISSUE TITLE
Script to upload OHRRPGCE stable releases to itch.io

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1217]
The OHRRPGCE's stable releases should be available on itch.io

We can use the butler tool to upload them.

See also #1213

**Comment by bob-the-hamster** [comment]
Done. Stable releases are now available from https://bob-the-hamster.itch.io/ohrrpgce and a script has been added to simplify uploading stable releases

**Comment by rversteegen** [comment]
Woo! What's with the "Version 1" description though, can that be fixed?

**Comment by bob-the-hamster** [comment]
Looks like I need to add the --userversion argument. I'll give it a try. Hope it supports unicode :D
