### ISSUE TITLE
importing scripts always fails on windows nightly build box when hspeak is built with euphoria 4.1.0

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1218]
On the windows nightly build box (Windows 7, Freebasic 1.08.1 mingw 8.1.0 euphoria 4.1.0) `scons test` always fails on the step that imports scripts into autotest.rpg

The error message is a red OHRRPGCE error, saying "Your copy of HSpeak is faulty or not supported. You should download a copy of HSpeak from http://rpg.hamsterrepublic.com/ohrrpgce/Downloads"

This error pops up when get_hspeak_version() returns failure. That function runs `hspeak -k` and parses the output.

On this windows box, running hspeak.exe -k from a cmd window appears to do nothing. control instantly returns to the shell. Sometimes 2 to 5 seconds later you may see a very rapid flash of the hspeak help screen opening and closing. It seems likely that run_and_get_output() is failing to get any output.

~I noticed this bug right after upgrading mingw from 5.3.0 -> 8.1.0 and right before upgrading euphoria from 4.0.5 -> 4.1.0~ (nope, wrong, I was confused)

I haven't run scons test on this windows box in a long time, so I don't really know when this started

**Comment by bob-the-hamster** [comment]
The last hspeak.exe generated by a nightly build, on 22 Sept 2021 at 1:08am works correctly when you run `hspeak -k`

Experimentally downgrading euphoria back down to 4.0.5 seems to have fixed the problem

**Comment by rversteegen** [comment]
If `hspeak -k` from the command opens a *separate* window that's because it's being compiled as a GUI rather than console program. And sure enough, the problem is that I forgot to pass `-con` to eubind, which is used for debug builds, which includes `scons test`. The euphoria version shouldn't have anything to do with it (I saw the same problem with 4.0.5). Fixed.

**Comment by bob-the-hamster** [comment]
Yep, that fixed it, thank you TMC!
I upgraded back to Euphoria 4.1.0 on the windows nightly build vm

**Comment by bob-the-hamster** [comment]
Argh, euphoria is failing differently now, not on scons test, but failing on a nightly build...

C:\Euphoria\bin\euc.exe -con -gcc hspeak.exw hsspiffy.e euphoria\io_with_unicode.e euphoria\ucstypes.e euphoria\unicode.e -verbose -maxsize 5000 -makefile -build-dir build\hspeak
option 'eudir' must not occur more than once in the command line.

Investigating...

**Comment by bob-the-hamster** [comment]
Ah, that last thing was easy enough to fix. In all my re-installing of different euphoria versions, the eu.ini file got all messed up. it had 4 **[all]** sections!

Should be fine now

**Comment by rversteegen** [comment]
Does eu.cfg (not eu.ini, right?) get appended to or modified during installation? I thought it just gets overwritten.
 
You seem to know already, but it might be worth mentioning that the error message is misleading, as (certain) eu.cfg contents are considered as command line arguments.
