### ISSUE TITLE
Android builds must target API level 30 and use new signature scheme

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1223]
Starting November 1 2021 any updates to apk files on Google Play must target API level 30 (Android 11), otherwise you will see an error like this, and will not be allowed to proceed with the upload:

> Your app currently targets API level 29 and must target at least API level 30 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 30

See also:
https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637713791388750052-2026131576&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console

**Comment by bob-the-hamster** [comment]
I managed to get the Android SDK on a copy of the Android nightly build vm upgraded, and I can now compile a working apk file that targets API level 30. I can sideload it, and it works, and seems okay.

Unfortunately there is another new requirement, so I'll add it to the scope of this task:

> You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme

**Comment by rversteegen** [comment]
I had a look at the API 30 changes, and it seems like the signature scheme v2 is the main change that concerns us, although there's yet another change to external storage permissions, which is probably not an additional problem since they're broken anyway? See #1226

**Comment by rversteegen** [comment]
James forgets to close again!

**Comment by bob-the-hamster** [comment]
Haha! Oh, actually, I wasn't quite done yet. I got it working on a clone of the Android nightly build machine, but I haven't actually swapped out the old VM and replaced it with the new one-- doesn't matter much for the nightly builds though
