### ISSUE TITLE
Valid attack targets aren't updated live while player is picking targets

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1233]
While a hero is selecting targets for an attack I think that the set of valid targets should be updated live. Currently, you can select targets that become invalid (e.g. because they jumped/became hidden, or (I presume) heroes that died/revived), and can't pick new targets that appear (e.g. because of spawning). If you don't set active-time battles to pause on menus and have enemies that hide, this is a pretty noticeable problem.

This is very closely related to #380, but that bug is about changes to the set of valid targets after you've selected your targets.

**Comment by bob-the-hamster** [comment]
Fixed in commit 463c43bb24144555b
