### ISSUE TITLE
Distributing a game for Mac from Windows is broken

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1239]
Recently Wobbler found that if you package a Mac app .zip from Windows it doesn't run on a Mac, and today I see Spendidland has [hit the same problem](https://splendidland.itch.io/franken). Distributing from Linux works.

Although I don't currently have access to a Mac to test, I assume the problem is that the unzipper built into Finder (no idea in which Mac OS version this started) no longer indiscriminately sets the +x bit on all files from a .zip created on Windows. zip files record which OS each file in the archive is from, with OS-specific metadata. Windows files don't have +x bits, so the zip format has no way to set them as executable.

Maybe we should disable the Distribute for Mac options until this is fixed? Spendidland resorted to telling Mac users to set the +x in the terminal.

I already wrote code to create .gz files but I don't want to expand it to .zip because it uses LodePNG's DEFLATE implementation, which compresses poorly in comparison to standard Info-ZIP. I think the easiest solution is to patch and compile our own zip.exe.

**Comment by rversteegen** [comment]
This is related to #963 which maybe should already be closed, but seems to list multiple bugs.

**Comment by bob-the-hamster** [comment]
This is a release blocker. The plan to fix it is to use zip_exec.exe from Galaxy Forces project (Public Domain) https://sourceforge.net/p/galaxyv2/code/HEAD/tree/other/zip_exec/zip_exec.cpp

TMC has already added it to our support executables, but I still need to write the code that actually uses it to fix the Mac app bundles on Windows

**Comment by bob-the-hamster** [comment]
I have implemented a fix in rev 12999 c98a14eb3904da264a2b4c5dc3641da17d421487
I've tested it on some VMs although I'll wait to close this bug until it gets at least just a little testing on real Windows and Mac machines

**Comment by bob-the-hamster** [comment]
I am marking this one closed. I am satisfied with the testing that I did on VMs
