### ISSUE TITLE
Enemy selection arrow not properly offset

### ISSUE THREAD

**Issue by Feenick** [ohrrpgce/ohrrpgce#1240]
![falsesky0147](https://user-images.githubusercontent.com/45484204/170319685-80d500af-a93c-47a1-a963-f0e7024f66ae.png)
![falsesky0146](https://user-images.githubusercontent.com/45484204/170319845-7ab0bfa4-8faf-44be-9388-214b736f77fb.png)

It's most obvious on large enemies, but I think the problem also carries over to the small/medium-sized ones as well.

**Comment by rversteegen** [comment]
Do you know whether this has changed recently? I imagine it's because of the recent switch to slices for the targeting cursor.

**Comment by Feenick** [comment]
Pretty sure it's recent. Ran an older version of the game on the stable release and it seems to be fine:

![falsesky0000](https://user-images.githubusercontent.com/45484204/170408925-a8dfad23-d6ef-4aeb-9933-1d24c348a845.png)

**Comment by bob-the-hamster** [comment]
I have to check the code to make sure, but I'll bet the old version
positioned the cursor relative to the hard-coded default enemy size even
for a non-default sized enemy, and the new version is positioning relative
to the top edge of the real sprite size.

**Comment by Feenick** [comment]
This guy's 75 pixels tall, and the targeting arrow seems to be fine in the stable version. First screen is in the stable version, third screen is in the nightly, and fourth screen is in the nightly with the targeting arrow moved to the top-left in the editor just for good measure.

![falsesky0148](https://user-images.githubusercontent.com/45484204/170499555-cf73593c-4cf1-456e-a5ba-619eafbc0429.png)
![falsesky0001](https://user-images.githubusercontent.com/45484204/170498759-6c2d921d-8837-412b-b7c0-1cc5a62c0061.png)
![falsesky0002](https://user-images.githubusercontent.com/45484204/170498760-037fc5dc-b959-4eed-a862-78725666aff3.png)
![falsesky0145](https://user-images.githubusercontent.com/45484204/170499286-cec8018f-11fb-4789-b3a8-374e712c9805.png)

**Comment by ohrrpgce-githubmail** [comment]
Oh! Haha! I checked the code and realized that when I converted the UI to
slices I simply forgot completely about the cursor offset. No wonder it
didn't work!

I can fix this 😄

**Comment by Feenick** [comment]
Cool. Do you have an ETA on when that would be?

**Comment by bob-the-hamster** [comment]
Oops! I got busy and then I forgot. I'll try to make time to fix it this
weekend.

**Comment by Feenick** [comment]
Sounds good. No rush, just thought I'd remind you.

**Comment by bob-the-hamster** [comment]
Oops! I went to fix this, and realized that I had already fixed it on May 28th. Please let me know if you are still seeing problems in nightly builds dated after that:

commit 538108e0bdf250933afb710b872089961080a58d
Author: james <james@7d344553-34f0-0310-a9b1-970ce8f1c3a2>
Date:   Sat May 28 00:00:42 2022 +0000

    Battle mouse hover cursor also respects enemy cursor offset again
    
    git-svn-id: https://rpg.hamsterrepublic.com/source/wip@12981 7d344553-34f0-0310-a9b1-970ce8f1c3a2

commit fc51b0aa7d77734ed237796d322fc716c1c33712
Author: james <james@7d344553-34f0-0310-a9b1-970ce8f1c3a2>
Date:   Sat May 28 00:00:34 2022 +0000

    Fix enemy cursor positioning in battle (was broken after the switch to slice-based battle ui)
    
    Also fixed cursor offset to actually match the position set in the enemy editor,
    rather than being offset 3 pixels to the left for no good reason. This also means
    that the default cursor position is the exact top center of the enemy sprite
    instead of 3 pixels to the left of the exact top center.
    
    This is technically a backcompat break, but since it is only 3 pixels, I don't want
    to bother with a backcompat bit and I hope nobodywill notice except for feenick,
    and I hope feenick will forgive me because it is more correct now!
    
    git-svn-id: https://rpg.hamsterrepublic.com/source/wip@12980 7d344553-34f0-0310-a9b1-970ce8f1c3a2
