### ISSUE TITLE
Feature Request: Remove Basic attack, and multiple types of MP.

### ISSUE THREAD

**Issue by IndegoRune** [ohrrpgce/ohrrpgce#1243]
Sorry if this is the wrong place to post this, just delete it if it's not.

I would like to request a way to turn off the basic attack. My planned battle system intends you to attack specific body parts, so the basic attack option is kind of pointless.

I would also like a way to have multiple types of MP to use. Like having both MP, and TP points, to spend, for either magic, or physical skills.

**Comment by rversteegen** [comment]
Please file unrelated feature suggestions (and bugs) as multiple issues.

What do you mean by "basic" attacks? The hero's weapon attack? You can remove that from the hero's battle menu in the hero editor. You'll need to edit each hero's battle menu separately.

As for multiple types of MP, that's covered by #1207 (More stats) plus #1121 (specifically arbitrary stat costs). As part of adding more stats you'll be able to select whether the stat behaves like MP (HP and MP are a bit different from the others). I actually already started on attack stat costs at some point.

**Comment by IndegoRune** [comment]
Roger. Thanks for the help.
