### ISSUE TITLE
waitforkeyrelease broken on some Linux boxes under unknown conditions

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1245]
On my Debian 11 box, I am suddenly having a problem with custom spawning external processes.

If I do Test Game, or try to compile my scripts with hspeak, custom seems to freeze.
If I click the X icon in the corner to make the window manager close the custom window, then it gets unstuck, and the external process launches. When I return to custom, it has gone to the save/quit menu

I don't believe this is related to a code change in the OHRRPGCE. I went back all the way to hrodvitnir, and it was still happening, so I think this could be a problem with my computer, or a very recent change in Debian, and our method of spawning external processes is just triggering it. (I have not seen any problems in any other programs besides the OHRRPGCE)

**Comment by rversteegen** [comment]
Coincidental for it to (retroactively) break right after I rewrote spawn_and_wait... (but that isn't used for Test Game anyway)

What are the last lines in c_debug.txt when importing scripts when it freezes? (Importing prints more than Test Game does)

**Comment by bob-the-hamster** [comment]
I'm confident nothing you changed recently broke it. It has to be something weird with my computer. I tested on one of the nightly build vms and it still works perfectly fine.

Here is c_debug.txt up to the freeze

```
 0.5  Full game data upgrade...
 0.5  Last edited by: [[OHRRPGCE wip 20220907.13112 gfx_sdl2+fb/music_sdl2 FreeBASIC 1.08.1 (2021-07-08) gcc 10.2.1 x86_64 buildname=  Built on eolo -g -exx FB_ERR=511 -gen gcc Linux 64-bit]] branch_rev 13112
 0.5  Upgraded by: OHRRPGCE wip 20171031.9622 gfx_sdl+fb/music_sdl FreeBASIC 1.05.0 (01-31-2016) x86    -g -exx Linux 32-bit
 0.5  archinym creation info: upgraded with RPGFIX.EXE 20000412
 0.5  ps -p 114161 -o comm= > "/home/james/.ohrrpgce/temp_stdout.990930.tmp" 2> "/home/james/.ohrrpgce/temp_stderr.985026.tmp"
 0.6  Joystick 0 GUID 030000006f0e0000a00200000f0100 instance_id 0
 0.6   Opened as gamecontroller XInput Controller
 0.6   Type: 2
 0.6  
 0.6  Opened joystick 0 PDP Xbox One Midnight Blue (id 0) -- 11 buttons 6 axes 1 hats 0 balls
48.3  Successfully opened IPC channel /home/james/.ohrrpgce/.lump_updates.txt
```

And there is nothing interesting after I un-stick it by trying to close the window

```
164.7  channel_write: pipe closed.
165.5  Cleaning up and terminating 0
165.5  Closing music backend...
165.6  ...done
168.3  Closing gfx backend & allmodex...
168.4  ...done
168.4  End.
```

**Comment by bob-the-hamster** [comment]
Okay, that was weird.

I updated all my packages, rebooted, and the problem just went away.

I am marking this closed. Not a valid bug (but definitely a weird thing)

**Comment by bob-the-hamster** [comment]
This happened again. I am not reopening, because I still think this is just me, but before I fixed it with a reboot, I confirmed that it still happens even with `-gfx fb` instead of the default sdl2 backend, and that doing a command-line import of scripts does not avoid the problem.

*Reboot sigh*

**Comment by rversteegen** [comment]
I'm aware of one thing that causes spawned programs to freeze (which then freezes Custom under Unix if it's waiting): if the program prints to stdout/err and it fills up the pipe buffer.

Try attaching gdb or seeing what the last thing in c_debug.txt is (since hspeak is invoked twice)

**Comment by bob-the-hamster** [comment]
Okay, I actually am reopening this one now. It keeps happening, and it is driving me crazy. Also sometimes rebooting doesn't fix it... also at least once, I managed to fix it by opening a new terminal window instead of rebooting (but can't reproduce again). Seems to be triggered by going into powersave mode, as far as I can tell

Also, even more importantly, I did some troubleshooting, and narrowed this down to waitforkeyrelease -- it actually has nothing to do with spawning external processes, that command is just mainly used when spawning external processes, but the spam debug menu command that uses it also freezes in the same way

**Comment by bob-the-hamster** [comment]
Okay, this was a dumb one.

My gamepad had fallen face-down on the floor. The analog stick was being pushed just so very slightly. I guess it was not enough to trigger movement when playing the game, but it was enough to make waitforkeyrelease get stuck.

The reason that rebooting my computer helped a few times is probably because the cord was right next to my computer and I bumped it with my foot while leaning over to check the power light

I have worked around this bug by adding logic to waitforkeyrelease so that if it waits a really long time, it starts to display the name of the scancode it is waiting for

**Comment by rversteegen** [comment]
Hah, that's amusingly dumb. That's a decent solution, but also a timeout would be reasonable; `waitforkeyrelease` was only intended to wait a couple ticks anyway.

`waitforkeyrelease` waits for a joystick analog stick exactly when it would register as a keypress in-game; it calls `anykeypressed` which calls `keyval`.

Stuck joystick buttons seem to be a very common problem. This must be at least the 3rd or 4th time I've heard of someone being confused by a depressed button on a gamepad that's plugged in but not in use. And my own PS1 controller has a permanently stuck thumbstick button when I turn on analog mode. Maybe we should automatically detect and ignore stuck buttons?

Plus also checking joystick buttons in Custom seems to cause a lot of problems because of reasons like this, so as I said before it's safer to just disable it by default.

**Comment by rversteegen** [comment]
And don't be so afraid of using gdb! I don't use a debugger enough either. Used to be more in the habit years ago...
