### ISSUE TITLE
Android 11: nightly builds fail with INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1249]
Topken reports:
> I am unable to install android nightlies as I get this error `INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.hamsterrepublic.ohrrpgce.game` so not sure how to proceed on my Samsung Galaxy Tab s5e

I think this is probably caused by this: https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme
> Users can't install or update apps that are only signed with APK Signature Scheme v1 on devices that run Android 11.

Probably a fix for this in upstream sdl-android.

**Comment by bob-the-hamster** [comment]
This sounds familiar. I think I may have already fixed this for packaged games, just not for the game player.

If I remember correctly, there were no code changes, I just had to upgrade the format of the signing certificates. I'm pretty sure I didn't do that for the debug certificate used by the game player

**Comment by rversteegen** [comment]
Regarding testing whether an .apk is correctly signed without needing an Android 11 installation, the link I gave suggested using apksigner (included in the Android SDK) to check:

```
> /opt/android-sdk-linux/build-tools/28.0.3/apksigner verify --verbose ~/Downloads/ohrrpgce-game-android-debug.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): false
Number of signers: 1
```

(I used a 2 year old .apk in this case but probably nothing has changed)

**Comment by bob-the-hamster** [comment]
I fixed this a while back by updating the debug.keystore that nightly builds were using
