### ISSUE TITLE
Nightly builds failing on Linux and Windows

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1250]
The nightly builds are failing on Windows and Linux vms
```
File "/home/james/src/nightly/ohrrpgce-build/wip/ohrbuild.py", line 20, in <module>
    from SCons.Script import Mkdir, Copy, Delete, Action   #These create Action nodes
ImportError: No module named 'SCons'
```
James speculates:
> Perhaps the version of scons I have on the nightly build vms is too old?

Ralph speculates:
> I see that error happened while running ohrpackage on one of the Linux VMs. When you invoke scons, it makes sure the python path is set up to include SCons. I think SCons should normally also be visible in the oridinary python environment. Maybe it's because it's running scons with python 2 and ohrpackage with python 3?

**Comment by bob-the-hamster** [comment]
I have narrowed down the simplest steps to reproduce this error
```
james@ixrat:~/src/nightly/ohrrpgce/wip$ python3
Python 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ohrbuild
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/src/nightly/ohrrpgce/wip/ohrbuild.py", line 20, in <module>
    from SCons.Script import Mkdir, Copy, Delete, Action   #These create Action nodes
ImportError: No module named 'SCons'
```
Interestingly enough, if I do the same thing in a different folder, it works

```
james@ixrat:~/src/ohr/wip$ python3
Python 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ohrbuild
```

In this case, `~/src/nightly/ohrrpgce/wip` is an almost completely pristine svn working copy, but `~/src/ohr/wip` where it works has a lot of accumulated cruft, all if which is ignored by svn. I just haven't figure out which bit of ignored cruft un-breaks it

**Comment by bob-the-hamster** [comment]
Oh! Duh! My `~/src/ohr/wip` was out of date. When I updated it, I can reproduce the error message there

This breakage started with svn rev 13158 which added this line to `ohrbuild.py`

```
from SCons.Script import Mkdir, Copy, Delete, Action   #These create Action nodes
```

I believe that these are only required for transpiling, so I can do a quick fix that will un-break everything else except transpiling

**Comment by rversteegen** [comment]
On my machine I'm able to `import SCons` in python3 (but not in python2, although I also have scons installed for python2). I don't know what the difference is.

The workaround you added is a correct fix, except the comment isn't. Transpiling will still work because the import should succeed when ohrbuild.py is imported by SConscript rather than by ohrpackage. So I just changed it slightly.

**Comment by bob-the-hamster** [comment]
Aha! That is indeed cleaner. Thank you TMC!
