### ISSUE TITLE
Upgrade Mac SDL2 framework

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1255]
We need to upgrade the Mac SLD2 framework on the nightly build vm (which is also the release build vm)

I'll just use the latest available Mac version, 2.26.5

**Comment by rversteegen** [comment]
You might as well upgrade SDL2_mixer too, to match Windows and Linux. I don't know which one is currently used.

**Comment by bob-the-hamster** [comment]
The latest Mac Frameworks seem to be:
SLD2 = 2.28.3
SLD2_mixer = 2.6.3

I have updated them both.
I also rewrote and renamed the script that downloads them, now it also installs them

**Comment by rversteegen** [comment]
Looking through the SDL changelog I notice:

2.26.5 (Apr 6 2023)
> The minimum deployment target on macOS is now 10.11, due to changes in the latest Xcode update

2.26.1 (Dec 2, 2022)
> Fixed building with older Xcode and macOS SDK

2.26.0 (Nov 22, 2022)
> Implemented vsync synchronization on macOS 12   [seems important; did Apple break the previous vsync support?]

2.24.0 (Aug 20, 2022):
> Bumped minimum OS deployment version to macOS 10.9

And there's not really anything interesting in 2.28.x (although unfortunately no list of bugfixes is provided).

This makes me wonder whether we should use SDL 2.26.4 instead to support older OS versions. According to our System Requirements page (which I'm not certain is up to date), "Mac OS 10.6-10.14 can run both the 32-bit or 64-bit apps". So it looks like this drops support for Mac OS 10.6-10.10 in the default build. (10.10 was released in 2014, 10.9 in 2013.) Although the 32-bit app supports those, noone is going to package their games with that. We need to at least update the requirements.

**Comment by rversteegen** [comment]
I see that you upgraded (`get_sdl_frameworks.sh`) from SDL 2.0.14 to 2.24.0 a year ago, which was presumably when we dropped support for OS 10.6-10.9 without realising it.

**Comment by bob-the-hamster** [comment]
So if I understand correctly, we should use version 2.26.4 and also update the requirements page to say that 10.10 is the minimum supported, yes?

**Comment by rversteegen** [comment]
10.9, but yes. It seems reasonable.

The requirement change to macOS 10.11+ is discussed here: https://github.com/libsdl-org/SDL/issues/7636
Supposedly before 2.24.0, SDL supported mac OS 10.7+, not 10.6. (IIRC macOS 10.6 has an incomplete set of 64-bit APIs so it's common to say 64-bit apps require 10.7+ but many will run on 10.6 too and I expected the OHR would.) And SDL still can be compiled to support 10.7+ provided you do it yourself; the change was made simply to support XCode 14.3 out of the box. If we ever feel like bothering we can do so (and use lastest SDL 2.x).

**Comment by bob-the-hamster** [comment]
Okay, I will reopen this issue so I remember to make the changes

**Comment by bob-the-hamster** [comment]
I changed the SDL2 framework to version 2.26.4
I also updated https://rpg.hamsterrepublic.com/ohrrpgce/System_Requirements
