### ISSUE TITLE
in menu editor, clicking/hovering is wrongly offset

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1257]
TMC recently noticed that mouse clicking/hovering in the menu editor is broken. it appears to be offset. This may bug may have been around for a while.

**Comment by rversteegen** [comment]
The F5 reload debug menu's MenuDef is now cut off (at 320px wide), indicating MenuDef positioning changed in a way I didn't intend. I think it's likely related.

**Comment by bob-the-hamster** [comment]
This bug was introduced at r12750 ( e5f2b4d8b240 ) on 2022-02-05
"Menu editor now shows how the menu is positioned at the in-game resolution"

This was the first revision that moved the menu preview to the bottom-right of the menu editor, so the mouse hover has always been offset for it.

**Comment by bob-the-hamster** [comment]
This was fixed in r13313 ( 9c268a9ee5e )

TMC, I think the "F5 reload debug menu's MenuDef is now cut off (at 320px wide)" thing was likely something different, file a separate bug if it is still a problem
