### ISSUE TITLE
Target cursors and damage digits appear behind battle menus

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1262]
The draw order of some battle UI (battle cursors/names, the battle menu, damage digits, and possibly more, needs checking) has changed, causing bugs like this Axe cop screenshot. A release blocker and needs fixing very soon. Introduced by battle slicification. See r12859 (cef934facc) which removed the old code to see how things used to be.

![AxeCop0021](https://github.com/ohrrpgce/ohrrpgce/assets/1165449/44ff20ce-d36b-4d7e-bc4f-3a123e108828)

I see two options for fixing this:
-instead of drawing the root slice, draw subtrees of it interspersed with drawing parts of the non-slicified UI
-add a ClassSlice to draw a MenuDef (the battle menu) so it can be put in the right place in the slice tree. I strongly prefer this option because it's quite easy, andrather than being a workaround is the first step towards slicifying menus, and can be used outside of battle too to finally allow people to display slices above menus.

**Comment by bob-the-hamster** [comment]
I have fixed this bug in r13312 ( d8537a82a7 )

ClassSlice is really nice! This is my first time looking at that code.

The MenuDefSlice is currently very unambitious, it just draws the menu in the correct order in the slice tree
I imagine later we could add features, like positioning the menu based on the slice position, or vice versa, snapping the slice position to the MenuDef position

At any rate, i am closing this bug now. One release blocker down!
