### ISSUE TITLE
Sprite slice cropping bug on emscripten web port only

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1269]
Tested with Vocabulary Mosaic. Also observed in PJ's Sponcon
Sprite slices that are set to crop children don't seem to work in the web port.

I'll try to reduce this to a minimal test case.

![image](https://github.com/ohrrpgce/ohrrpgce/assets/3442937/4bb2aad5-8030-415e-9940-5691b151c0f3)
![image](https://github.com/ohrrpgce/ohrrpgce/assets/3442937/e259d9cd-03ca-485e-9c99-3eef6c8d8b1f)

**Comment by bob-the-hamster** [comment]
Okay, This was not hard to confirm with a web build of custom, and a simple 2-slice collection.

"Clip Children: Yes" simple seems to be ignored

![image](https://github.com/ohrrpgce/ohrrpgce/assets/3442937/b8faed80-67f6-4a17-b05a-d3029178cd0c)

**Comment by bob-the-hamster** [comment]
I can reproduce this on Linux if I compile with `scons minos=1`

I see this in `config.bi`
```
#if defined(MINIMAL_OS)
 #define NO_TLS
#endif
```

And in `allmodex.bas` in the `get_cliprect` function I see this:
```
function get_cliprect(fr as Frame ptr = NULL) byref as ClipState
	#ifdef NO_TLS
		static cliprect as ClipState
		if fr then setclip , , , , fr
		return cliprect
	#else
```
So I think the minos NO_TLS logic is wrong for slice that need to clip.

**Comment by rversteegen** [comment]
Yikes! Looking into it now.
