### ISSUE TITLE
Mouse/Touch dismount from vehicles

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#29]
It is currently not possible to dismount certain vehicles using on the mouse/touch interface

This needs to be fixed. Clicking on a valid dismount point should dismount

Specifically I know that dismount-ahead ships don't work.

**Comment by bob-the-hamster** [comment]
Actually, this DOES work, just not quite as nicely as I would like.

A dismount-ahead ship can be dismounted by clicking on the ship. That is fine, but we *also* need it to dismount when you touch one tile ahead of the vehicle

**Comment by bob-the-hamster** [comment]
Fixed! Now you can click on a shoreline, and a boat will properly let you dismount where you clicked. 

It will dismount if you click in the middle of a continent, and it will not dismount early if you collide with a shoreline before you reach the specific coastline tile that you clicked on

**Comment by rversteegen** [comment]
Oh, that's pretty neat.

I haven't tested it, but I notice `user_triggered_vehicle_use_action()` returns true if you click anywhere except on the hero. Is that correct? I suppose that if you click on a reachable tile then the hero will start pathfinding (`update_hero_pathfinding`, which is called before `update_vehicle_state`, will set x/ygo, which disables vehicle controls), but there are so many edge cases, like if you click on a tile outside pathfinidng range.

**Comment by bob-the-hamster** [comment]
You mis-read user_triggered_vehicle_use_action()
That function returns true if you click on the hero, not if you click
elsewhere.
That is for use actions like the script to dismount the myrmidon suit in
Wandering Hamster.

**Comment by rversteegen** [comment]
Whooops!
