### ISSUE TITLE
Virus scanners raise false alarm on game.exe when a game icon is embedded

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#38]
In October 2018 Wobbler reported that distributing a game, embedding the game icon into game.exe (using rcedit), produced a modified game.exe flagged by many virus scanners:  virustotal reported 14 detections (mainly Gen:Heur.Conjar.9), regardless of the icon embedded.
Last month ago I tested again and the problem had gone away, only SecureAge APEX reporting a problem.
At the time I found that it didn't make any difference *which* .ico was embedded, and there were no detections if the .ico was compiled in directly instead of embedded with rcedit.

But this month the problem is back! [Virustotal again reports](https://www.virustotal.com/gui/file/ae623459717d7ca2e6b937f57c99dbfe9539db588749fec2423c7e4739fc6369/detection) 14 detections for Gen:Heur.Conjar.9!

sneakfest.exe used the Aug 14 nightly, so I tried again with latest nightly and testgame/test.{rpg,ico}. It got only [8 detections](https://www.virustotal.com/gui/file/c4d39d05a77466cf177677de42e920fae445bc3002e9988fb67527080bfe332e/detection) for test.zip and [10 detections](https://www.virustotal.com/gui/file/8f50c5511fdd053354145c59286754df33d03e4d4416f48b79022196fe2db075/detection) for test.exe. (Only SecureAge APEX finds the unmodified nightly game.exe as malicious)

**Comment by rversteegen** [comment]
I thought that maybe compiling game.exe with no icon would be a workaround, but I can't test it, because when I build game.exe I get no detections either [with](https://www.virustotal.com/gui/file/f3dcc45c429092484c4cf68682b98517052dc30de3696d0cf1280071ef7d0ad9/detection) or [without](https://www.virustotal.com/gui/file/9ae5b9d107f2d777801fb1f9df82f59effc9d89c717e63bc0880e7da7c1e0dd6/detection) embedding an .ico!

**Comment by rversteegen** [comment]
I tried reanalysing the file in my first virus total link, and now the detection rate jumped from 14 to 18/67 :(  Including most notably Microsoft, McAfee, TrendMicro-HouseCall and BitDefender. There are a range of different detections, beyond "Gen:Heur.Conjar.9" also "Trojan:Win32/Tiggre!plock" "TROJ_GEN.R002H09HH19", "Malicious (high Confidence)", etc.

**Comment by bob-the-hamster** [comment]
Maybe this one is serious enough that we should (for now) disable the icon embedding feature from the Distribute Game menu?

**Comment by rversteegen** [comment]
Yes, no icon would be much better than a lot of confusion and worried players. We could pop up a message explaining the problem, and giving the choice of whether to embed.

**Comment by rversteegen** [comment]
OK, I've added a prompt asking whether to embed an .ico with a warning about virus scanners. The default is 'no'.

I've retested on virustotal and detections dropped slightly to 16/71. Still 0 detections for the game.exe I compiled on my machine (back in August). The fact that they don't detect that one gives me some hope.

There's also a recent thread on the FB forums complaining about FB programs being misdetected, but it seems not very related https://freebasic.net/forum/viewtopic.php?f=17&t=28010

**Comment by rversteegen** [comment]
I retested that file from August and detections are still 15/70. I tried the latest nightly with kaiju.ico embedded and the number of detected has [dropped to 11/71](https://www.virustotal.com/gui/file/7cacc6e086b4897e5e19ee33ee9ff667add0dcebaf5ae6dcb2f4d7b95160b5c9/detection), no longer including most of the major virus scanners. The only ones I've heard of are BitDefender and Ad-Aware.

So maybe we can wait it out. Or maybe the reduction in detection rate was just due to a different icon.
A possible workaround is to upgrade/change the compiler. I'm using a mingw-w64 crosscompiler (GCC 4.5) and a more recent fbc, while the nightly build machine uses mingw with GCC 5.3 and fbc 1.05. I also tried compiling on Windows, with mingw (GCC 4.8.1) and fbc 1.04 and [got just one detection](https://www.virustotal.com/gui/file/a43737bcb6b40da586b42879da5acf70aa44a8a0e814d88e01c02722c5ae05cb/details) (Sangfor Engine Zero) embedding kaiju.ico.

Aside, comparing the sizes of the exes:
Official nightly mingw gcc 5.3: 3.06 MB
mingw-w64 gcc 4.5 (cross-compile): 2.65 MB
mingw gcc 4.8.1:  2.42 MB

**Comment by bob-the-hamster** [comment]
I am scared to upgrade the mingw gcc on the nightly build box, but if you think it is a good idea, I can try it

**Comment by rversteegen** [comment]
Well, maybe it isn't a good idea immediately before release, for the risk of breaking the build system*. I don't think there's much risk of introducing bugs into game.exe.

*Though, you could snapshot the VM in case.

**Comment by rversteegen** [comment]
Actually come to think of it, changing compiler version could quite easily would break stuff like Win9X support and crash reporting symbols resolution.

And there's fewer virus scanners now flagging a problem anyway.

**Comment by bob-the-hamster** [comment]
That works out, since I didn't have time to change the compiler yet this week. I'll leave it alone for now

**Comment by rversteegen** [comment]
> I retested that file from August and detections are still 15/70. I tried the latest nightly with kaiju.ico embedded and the number of detected has [dropped to 11/71](https://www.virustotal.com/gui/file/7cacc6e086b4897e5e19ee33ee9ff667add0dcebaf5ae6dcb2f4d7b95160b5c9/detection), no longer including most of the major virus scanners. The only ones I've heard of are BitDefender and Ad-Aware.

Bad news, had another look, and I see that that file was reanalysed a week later (I don't remember doing that), and detections jumped back up to 18, again including TrendMicro, McAfee and Windows Defender (which detects it as "Presenoker"). Reanalysed and now it's 19/71. So this problem has not gone away at all.

**Comment by rue9x** [comment]
Some of the games _with_ embedded icons are showing up as viruses as well. I use Windows Security essentials and Moonday (https://www.slimesalad.com/forum/viewgame.php?t=8044) comes up as a virus (as the author had warned). I'm not sure how she added the icon/cleverly disguised virus.

**Comment by rversteegen** [comment]
Yes, the problem here is that games with embedded icons cause false positives. I'm sure Moonday had an icon embedded into game.exe in the normal way using Custom.

We still can try upgrading the compilers on the nightly build machine and hope that fixes it.

I suppose we could look for a different program that can embed icons. I haven't tried that.

**Comment by rversteegen** [comment]
Number of detections (following [previous link](https://www.virustotal.com/gui/file/7cacc6e086b4897e5e19ee33ee9ff667add0dcebaf5ae6dcb2f4d7b95160b5c9/detection)) has increased back to 16/68 and includes many popular scanners like Microsoft, McAfee  Bitdefender and TrendMicro.

Prifurin suggested that we use ResourceHacker instead to embed icons. It's freeware but not redistributable, so Custom would have to download it from the official site. A 3MB download, not bad, but much larger than rcedit. It has a commandline option to embed icons.

**Comment by rversteegen** [comment]
This is almost solved!

Firstly, rescanning the previous file, the number of detections dropped to just 7/66 (including Microsoft and McAfee). But they're detecting it based on learning from the previous false positive I think. Embedding an icon in a fresh nightly copy of game.exe produces just 2/66 detections, from only obscure scanners.

Looking at the rcedit issue tracker I discovered that this problem is caused by rcedit not updating the .exe checksum, so I fixed rcedit to do so, solving the problem! 0/66 detections.

However I compiled rcedit using Visual Studio 2019 using the "v141_xp" toolchain which supposedly targets Windows XP. Unfortunately, [it doesn't actually](https://developercommunity.visualstudio.com/t/visual-studio-1692-breaks-windows-xp-targeting/1383023), the compiled rcedit.exe doesn't run on Win XP, even when statically linking the C runtime. It looks like I would have to install a copy of VS 2015 together with another toolchain and Windows SDK, what a nightmare.
Maybe I'll just write a 10-line FB function to compute and set the checksum (which is far simpler than doing it using the winapi checksum function!) I might need such a utility anyway for embedding data files in game/custom.exe.

**Comment by bob-the-hamster** [comment]
Oh, nice!

And the workaround of fixing the checksum with an fb function is clever!

If this is so close to being fixed, I'll hold off on branching hrodvitir
just a little longer, but I think this is the last thing we need.

I'm also going to start begging for release-candidate testing right now-- I
am hoping to keep the RC testing cycle as short as reasonable possible,
since I think the nightly wips are already quite stable, and + releases are
not hard.

---
James

**Comment by rversteegen** [comment]
Hmm, "fixing #38" commit message doesn't autoclose.

I'm working on a few more last minute fixes, but nothing urgent... and I'm going to bed. Turns out SDL/SDL2_mixer MIDI playback was broken by my distro updating yet again...

It would be best to have people test release builds of hróðvitnir, to catch any remaining problems with non-ascii codename characters (I already did some testing last year). Recall that codename.txt lets you set "hrodvitnir" as the svn branch name, but that's used almost nowhere.

**Comment by bob-the-hamster** [comment]
It just occurred to me that after we branch and change the codename, the
distribute menu in those builds will be straight up broken until the stable
release is actually final.

I guess that is a good argument in favor of a nearly immediate hrodvitnir
release, with a + release to follow when needed.

And thank you for mentioning the svn branch name in codename.txt I had
forgotten about that!

---
James

**Comment by rversteegen** [comment]
> It just occurred to me that after we branch and change the codename, the distribute menu in those builds will be straight up broken until the stable release is actually final.

Well we'd need to temporarily place all the 'minimal' builds in hamsterrepublic.com/ohrrpgce/dl/ so that people could actually test packaging games. That's not going to cause any additional problems for users of old versions that wouldn't happen anyway on the actual release, unless the RC is seriously broken.
