### ISSUE TITLE
Numpad keys never mapped to arrow keys/etc regardless of Numlock (gfx backend specific)

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#45]
Our backends are inconsistent about numpad handling. In gfx_sdl, gfx_sdl2 and gfx_directx, unlike gfx_fb, the numpad can't be used for hero or cursor movement (up/down/pgdn/etc) because they are never mapped to other keys, and we don't explicitly check for numpad keys for hero or menu cursor movement -- with the exception of Numpad Enter for Use/Confirm.

When using gfx_fb, if numlock is off, then pressing numpad keys causes an arrow key/pageup/etc to be reported as pressed instead. (Though gfx_fb can't distinguish a few keys: numpad /, - and Enter.) Also gfx_fb doesn't report whether Numlock, Pause or PrntScrn are on or not, only Capslock and Scrolllock act normal. Behaviour seems to be the same across Windows and Linux.

In gfx_directx, gfx_sdl and gfx_sdl2, Numlock makes no difference to how keys are reported. They are never mapped to arrow keys/etc.

(I didn't test and don't care about gfx_alleg and gfx_console.)

In gfx_sdl (both Windows+Linux act the same:) Numlock is reported as depressed when it's on, not when the key is actually depressed. Numlock only becomes undepressed when you turn it off and then press a numpad key. Also if Numlock is on when you start the program, it doesn't know, and its state will always read as inverted from actual.
Scrolllock and Capslock act like normal keys on Windows and Linux.  PrtScrn and Pause act normally on Linux, but on Windows act weird, they spend keydown events but are never depressed.

gfx_directx is similar to gfx_sdl. I read Numlock, Capslock and Scrolllock as depressed when they're on, but Numlock only goes up when you turn it off and then press a numpad key. PrntScrn is a normal key, Pause reports keydowns but is never depressed.

gfx_sdl2 returns the true down/up state of all keys on the keyboard including Scrolllock (but this might change, I have to make changes to gfx_sdl2's key handling because it doesn't respect xmodmap remapping). 

Maybe we should change gfx_directx, gfx_sdl, gfx_sdl2 to act like gfx_fb (or handle it in allmodex), so you can use numlock to decide whether/how to use the numpad.

**Comment by bob-the-hamster** [comment]
I would be inclined to vote for gfx_sdl's behavior as being the most appropriate. Emulating it in other backends (when possible) probably seems best

**Comment by rversteegen** [comment]
Argh! I completely mixed up gfx_sdl with the others! Actually gfx_sdl behaves most like gfx_directx; it doesn't do any remapping of numpad. I'm going to edit my original post for clarity.

So, you think that the numpad should *not* be usable for movement at all, regardless of numlock?
An old-timer complained that the numpad used to be usable for movement in DOS (it also was in early the gfx_fb-based Windows port).

Maybe we could have a setting to allow the numpad for movement in Custom depending on numlock (currently, except with gfx_fb, it's always for entering numbers only) and also add a per-game setting. Some games will want to script special-purpose separate controls for the numpad or manually check `key:numpad 1` etc for numeric input, but 99% would have no problem with them being mapped to normal movement.

But... this seems too unimportant to spend time on.

(...Also, I would like to implement 8-directional movement in the OHR anyway. Maybe we could use script constants 0.5 = upright, 1.5 = downright, etc.)

**Comment by rversteegen** [comment]
Oh, sorry, I confused the backends again; when you suggested following (what I erroneously wrote about) gfx_sdl, you meant respecting numlock to switch between movement and numeric input/separate numpad keypresses.

**Comment by rversteegen** [comment]
I edit my description of the backends in the first post. It sure is a pain to keep track of all the differences across backends and OSes.

**Comment by bob-the-hamster** [comment]
Nah, I suggested following gfx_sdl because it is all I have used for like 10 years.

 I do see now that the original discription was inaccurate, and the fact that didn't trip me up is apparently a testament to how poorly I was paying attention ;)

**Comment by rversteegen** [comment]
OK. I've recategorised this as a feature request. Maybe it'll happen as part of making built-in controls remappable.

**Comment by rversteegen** [comment]
In r11633 (c897fb1f) I made allmodex map numpad to arrows/home/end etc when numlock is off (and also, fixed --no-native-kbd so the numpad only generates text input when numlock on xor shift pressed, to match native text input). So turn numlock on to either use the numpad for text input or to get separate unmapped numpad keys. This is similar to how gfx_fb (and QuickBasic) behave.

You can disable the remapping by pressing Ctrl-Shift-N in Game/Custom or using the `--nonumpad` cmdline option.

I've now finished fixing all the gfx backends to report the numlock state correctly so that the numpad remapping works right (r11677-11679). Otherwise you got both text input and cursor movement at the same time.
Remapping isn't needed in gfx_fb and is disabled there.
