### ISSUE TITLE
Fix Windows 10 fullscreen bug with gfx_directx

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#7]
Fix Windows 10 fullscreen bug with gfx_directx (Was this also broken in Ethedreme? If so it is not a fufluns blocker)

**Comment by rversteegen** [comment]
I was under the impression that this problem (which appeared to be a Windows 10 bug) was no longer present. Just tested in Win10 1903 and it's gone.
