### ISSUE TITLE
Crash in tag browser autoset tags detail viewer

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#9]
There's a nasty crash in the tag browser autoset tags detail viewer

need to verify if this is same or different than "crash when I tried to assign the same "is equipped by active hero" tag to more than one item"

**Comment by rversteegen** [comment]
Fixed in r11216.
Was introduced in December.

It was the same as the crash when autosetting the same tag in multiple places, since that calls `tag_autoset_warning` which calls `describe_tag_autoset_places`.
